
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Greek.ipynb
from exp.Variables import makeVar, Var

class GreekSymbols():
    def __init__(self):
        pass
    @property
    def alpha(self):
        return Var(r'\alpha')
    @property
    def Alpha(self):
        return Var(r'\Alpha')
    @property
    def beta(self):
        return Var(r'\beta')
    @property
    def Beta(self):
        return Var(r'\Beta')
    @property
    def gamma(self):
        return Var(r'\gamma')
    @property
    def delta(self):
        return Var(r'\delta')
    @property
    def Delta(self):
        return Var(r'\Delta')
    @property
    def epsilon(self):
        return Var(r'\epsilon')
    @property
    def zeta(self):
        return Var(r'\zeta')
    @property
    def varepsilon(self):
        return Var(r'\varepsilon')
    @property
    def eta(self):
        return Var(r'\eta')
    @property
    def theta(self):
        return Var(r'\theta')
    @property
    def vartheta(self):
        return Var(r'\vartheta')
    @property
    def Theta(self):
        return Var(r'\Theta')
    @property
    def iota(self):
        return Var(r'\iota')
    @property
    def kappa(self):
        return Var(r'\kappa')
    @property
    def lambd(self):
        return Var(r'lambda')
    @property
    def Lambd(self):
        return Var(r'\Lambda')
    @property
    def mu(self):
        return Var(r'\mu')
    @property
    def pi(self):
        return Var(r'\pi')
    @property
    def Pi(self):
        return Var(r'\Pi')


"default symbol lookup class, can change name later maybe"
Greek = GreekSymbols()