
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Operators.ipynb
from exp.Variables import makeVar, Var, wrap

class OperatorSymbols():
    def __init__(self):
        pass
    @property
    def leq(self):
        return Var(r'\leq')
    @property
    def leqq(self):
        return Var(r'\leqq')
    @property
    def leqslant(self):
        return Var(r'\leqslant')
    @property
    def geq(self):
        return Var(r'\geq')
    @property
    def geqq(self):
        return Var(r'\geqq')
    @property
    def geqslant(self):
        return Var(r'\geqslant')
    @property
    def nless(self):
        return Var(r'\nless')
    @property
    def nleq(self):
        return Var(r'\nleq')
    @property
    def lneq(self):
        return Var(r'\lneq')
    @property
    def nleqq(self):
        return Var(r'\nleqq')
    @property
    def lneqq(self):
        return Var(r'\lneqq')
    @property
    def lvertneqq(self):
        return Var(r'\lvertneqq')
    @property
    def nleqslant(self):
        return Var(r'\nleqslant')
    @property
    def ngtr(self):
        return Var(r'\ngtr')
    @property
    def ngeq(self):
        return Var(r'\ngeq')
    @property
    def gneq(self):
        return Var(r'\gneq')
    @property
    def ngeqq(self):
        return Var(r'\ngeqq')
    @property
    def gneqq(self):
        return Var(r'\gneqq')
    @property
    def gvertneqq(self):
        return Var(r'\gvertneqq')
    @property
    def ngeqslant(self):
        return Var(r'\ngeqslant')
    @property
    def vartriangleleft(self):
        return Var(r'\vartriangleleft')
    @property
    def trianglelefteq(self):
        return Var(r'\trianglelefteq')
    @property
    def lesssim(self):
        return Var(r'\lesssim')
    @property
    def lessapprox(self):
        return Var(r'\lessapprox')
    @property
    def prec(self):
        return Var(r'\prec')
    @property
    def preceq(self):
        return Var(r'\preceq')
    @property
    def precsim(self):
        return Var(r'\precsim')
    @property
    def precapprox(self):
        return Var(r'\precapprox')
    @property
    def vartriangleright(self):
        return Var(r'\vartriangleright')
    @property
    def trianglerighteq(self):
        return Var(r'\trianglerighteq')
    @property
    def gtrsim(self):
        return Var(r'\gtrsim')
    @property
    def gtrapprox(self):
        return Var(r'\gtrapprox')
    @property
    def succ(self):
        return Var(r'\succ')
    @property
    def succeq(self):
        return Var(r'\succeq')
    @property
    def succsim(self):
        return Var(r'\succsim')
    @property
    def succapprox(self):
        return Var(r'\succapprox')
    @property
    def ntriangleleft(self):
        return Var(r'\ntriangleleft')
    @property
    def ntrianglelefteq(self):
        return Var(r'\ntrianglelefteq')
    @property
    def lnsim(self):
        return Var(r'\lnsim')
    @property
    def lnapprox(self):
        return Var(r'\lnapprox')
    @property
    def nprec(self):
        return Var(r'\nprec')
    @property
    def npreceq(self):
        return Var(r'\npreceq')
    @property
    def precnsim(self):
        return Var(r'\precnsim')
    @property
    def precnapprox(self):
        return Var(r'\precnapprox')
    @property
    def ntriangleright(self):
        return Var(r'\ntriangleright')
    @property
    def ntrianglerighteq(self):
        return Var(r'\ntrianglerighteq')
    @property
    def gnsim(self):
        return Var(r'\gnsim')
    @property
    def gnapprox(self):
        return Var(r'\gnapprox')
    @property
    def nsucc(self):
        return Var(r'\nsucc')
    @property
    def nsucceq(self):
        return Var(r'\nsucceq')
    @property
    def succnsim(self):
        return Var(r'\succnsim')
    @property
    def succnapprox(self):
        return Var(r'\succnapprox')
    @property
    def eqslantless(self):
        return Var(r'\eqslantless')
    @property
    def lessgtr(self):
        return Var(r'\lessgtr')
    @property
    def lesseqgtr(self):
        return Var(r'\lesseqgtr')
    @property
    def lesseqqgtr(self):
        return Var(r'\lesseqqgtr')
    @property
    def eqslantgtr(self):
        return Var(r'\eqslantgtr')
    @property
    def gtrless(self):
        return Var(r'\gtrless')
    @property
    def gtreqless(self):
        return Var(r'\gtreqless')
    @property
    def gtreqqless(self):
        return Var(r'\gtreqqless')
    @property
    def ll(self):
        return Var(r'\ll')
    @property
    def lll(self):
        return Var(r'\lll')
    @property
    def lessdot(self):
        return Var(r'\lessdot')
    @property
    def preccurlyeq(self):
        return Var(r'\preccurlyeq')
    @property
    def curlyeqprec(self):
        return Var(r'\curlyeqprec')
    @property
    def gg(self):
        return Var(r'\gg')
    @property
    def ggg(self):
        return Var(r'\ggg')
    @property
    def gtrdot(self):
        return Var(r'\gtrdot')
    @property
    def succcurlyeq(self):
        return Var(r'\succcurlyeq')
    @property
    def curlyeqsucc(self):
        return Var(r'\curlyeqsucc')