
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Arrow.ipynb
from pytex.Variable import Var
class ArrowsSymbols():
    def __init__(self):
        pass
    @property
    def Leftarrow(self):
        return Var(r'\Leftarrow')
    @property
    def leftharpoonup(self):
        return Var(r'\leftharpoonup')
    @property
    def leftharpoondown(self):
        return Var(r'\leftharpoondown')
    @property
    def leftleftarrows(self):
        return Var(r'\leftleftarrows')
    @property
    def rightarrow(self):
        return Var(r'\rightarrow')
    @property
    def Rightarrow(self):
        return Var(r'\Rightarrow')
    @property
    def rightharpoonup(self):
        return Var(r'\rightharpoonup')
    @property
    def rightharpoondown(self):
        return Var(r'\rightharpoondown')
    @property
    def rightrightarrows(self):
        return Var(r'\rightrightarrows')
    @property
    def uparrow(self):
        return Var(r'\uparrow')
    @property
    def Uparrow(self):
        return Var(r'\Uparrow')
    @property
    def upharpoonleft(self):
        return Var(r'\upharpoonleft')
    @property
    def upharpoonright(self):
        return Var(r'\upharpoonright')
    @property
    def upuparrows(self):
        return Var(r'\upuparrows')
    @property
    def downarrow(self):
        return Var(r'\downarrow')
    @property
    def Downarrow(self):
        return Var(r'\Downarrow')
    @property
    def downharpoonleft(self):
        return Var(r'\downharpoonleft')
    @property
    def downharpoonright(self):
        return Var(r'\downharpoonright')
    @property
    def downdownarrows(self):
        return Var(r'\downdownarrows')
    @property
    def longleftarrow(self):
        return Var(r'\longleftarrow')
    @property
    def Longleftarrow(self):
        return Var(r'\Longleftarrow')
    @property
    def hookleftarrow(self):
        return Var(r'\hookleftarrow')
    @property
    def leftrightharpoons(self):
        return Var(r'\leftrightharpoons')
    @property
    def leftrightarrows(self):
        return Var(r'\leftrightarrows')
    @property
    def Lleftarrow(self):
        return Var(r'\Lleftarrow')
    @property
    def Lsh(self):
        return Var(r'\Lsh')
    @property
    def leftarrowtail(self):
        return Var(r'\leftarrowtail')
    @property
    def twoheadleftarrow(self):
        return Var(r'\twoheadleftarrow')
    @property
    def curvearrowleft(self):
        return Var(r'\curvearrowleft')
    @property
    def circlearrowleft(self):
        return Var(r'\circlearrowleft')
    @property
    def looparrowleft(self):
        return Var(r'\looparrowleft')
    @property
    def longrightarrow(self):
        return Var(r'\longrightarrow')
    @property
    def Longrightarrow(self):
        return Var(r'\Longrightarrow')
    @property
    def hookrightarrow(self):
        return Var(r'\hookrightarrow')
    @property
    def rightleftharpoons(self):
        return Var(r'\rightleftharpoons')
    @property
    def rightleftarrows(self):
        return Var(r'\rightleftarrows')
    @property
    def Rrightarrow(self):
        return Var(r'\Rrightarrow')
    @property
    def Rsh(self):
        return Var(r'\Rsh')
    @property
    def rightarrowtail(self):
        return Var(r'\rightarrowtail')
    @property
    def twoheadrightarrow(self):
        return Var(r'\twoheadrightarrow')
    @property
    def curvearrowright(self):
        return Var(r'\curvearrowright')
    @property
    def circlearrowright(self):
        return Var(r'\circlearrowright')
    @property
    def looparrowright(self):
        return Var(r'\looparrowright')
    @property
    def leftrightarrow(self):
        return Var(r'\leftrightarrow')
    @property
    def longleftrightarrow(self):
        return Var(r'\longleftrightarrow')
    @property
    def updownarrow(self):
        return Var(r'\updownarrow')
    @property
    def nleftarrow(self):
        return Var(r'\nleftarrow')
    @property
    def nrightarrow(self):
        return Var(r'\nrightarrow')
    @property
    def nleftrightarrow(self):
        return Var(r'\nleftrightarrow')
    @property
    def Leftrightarrow(self):
        return Var(r'\Leftrightarrow')
    @property
    def Longleftrightarrow(self):
        return Var(r'\Longleftrightarrow')
    @property
    def Updownarrow(self):
        return Var(r'\Updownarrow')
    @property
    def nLeftarrow(self):
        return Var(r'\nLeftarrow')
    @property
    def nRightarrow(self):
        return Var(r'\nRightarrow')
    @property
    def nLeftrightarrow(self):
        return Var(r'\nLeftrightarrow')
    @property
    def mapsto(self):
        return Var(r'\mapsto')
    @property
    def longmapsto(self):
        return Var(r'\longmapsto')
    @property
    def multimap(self):
        return Var(r'\multimap')
    @property
    def rightsquigarrow(self):
        return Var(r'\rightsquigarrow')
    @property
    def leftrightsquigarrow(self):
        return Var(r'\leftrightsquigarrow')
    @property
    def swarrow(self):
        return Var(r'\swarrow')
    @property
    def searrow(self):
        return Var(r'\searrow')
    @property
    def nwarrow(self):
        return Var(r'\nwarrow')
    @property
    def nearrow(self):
        return Var(r'\nearrow')

Arrow = ArrowsSymbols()