
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Greek.ipynb
from pytex.Variables import makeVar, Var

class GreekSymbols():
    def __init__(self):
        pass
    @property
    def beta(self):
        return Var(r'\beta')
    @property
    def gamma(self):
        return Var(r'\gamma')
    @property
    def delta(self):
        return Var(r'\delta')
    @property
    def epsilon(self):
        return Var(r'\epsilon')
    @property
    def zeta(self):
        return Var(r'\zeta')
    @property
    def eta(self):
        return Var(r'\eta')
    @property
    def theta(self):
        return Var(r'\theta')
    @property
    def iota(self):
        return Var(r'\iota')
    @property
    def kappa(self):
        return Var(r'\kappa')
    @property
    def lambd(self):
        return Var(r'\lambda')
    @property
    def mu(self):
        return Var(r'\mu')
    @property
    def nu(self):
        return Var(r'\nu')
    @property
    def xi(self):
        return Var(r'\xi')
    @property
    def mathrm(self):
        return Var(r'\mathrm')
    @property
    def pi(self):
        return Var(r'\pi')
    @property
    def rho(self):
        return Var(r'\rho')
    @property
    def sigma(self):
        return Var(r'\sigma')
    @property
    def tau(self):
        return Var(r'\tau')
    @property
    def upsilon(self):
        return Var(r'\upsilon')
    @property
    def phi(self):
        return Var(r'\phi')
    @property
    def chi(self):
        return Var(r'\chi')
    @property
    def psi(self):
        return Var(r'\psi')
    @property
    def omega(self):
        return Var(r'\omega')
    @property
    def varepsilon(self):
        return Var(r'\varepsilon')
    @property
    def vartheta(self):
        return Var(r'\vartheta')
    @property
    def varkappa(self):
        return Var(r'\varkappa')
    @property
    def varpi(self):
        return Var(r'\varpi')
    @property
    def varrho(self):
        return Var(r'\varrho')
    @property
    def varphi(self):
        return Var(r'\varphi')
    @property
    def varsigma(self):
        return Var(r'\varsigma')
    @property
    def Gamma(self):
        return Var(r'\Gamma')
    @property
    def Delta(self):
        return Var(r'\Delta')
    @property
    def Theta(self):
        return Var(r'\Theta')
    @property
    def Lambda(self):
        return Var(r'\Lambda')
    @property
    def Upsilon(self):
        return Var(r'\Upsilon')
    @property
    def Xi(self):
        return Var(r'\Xi')
    @property
    def Phi(self):
        return Var(r'\Phi')
    @property
    def Pi(self):
        return Var(r'\Pi')
    @property
    def Psi(self):
        return Var(r'\Psi')
    @property
    def Sigma(self):
        return Var(r'\Sigma')
    @property
    def Omega(self):
        return Var(r'\Omega')
    @property
    def digamma(self):
        return Var(r'\digamma')
    @property
    def aleph(self):
        return Var(r'\aleph')
    @property
    def beth(self):
        return Var(r'\beth')
    @property
    def gimel(self):
        return Var(r'\gimel')
    @property
    def daleth(self):
        return Var(r'\daleth')
    @property
    def forall(self):
        return Var(r'\forall')
    @property
    def exists(self):
        return Var(r'\exists')
    @property
    def nexists(self):
        return Var(r'\nexists')
    @property
    def Finv(self):
        return Var(r'\Finv')
    @property
    def Game(self):
        return Var(r'\Game')
    @property
    def backepsilon(self):
        return Var(r'\backepsilon')
    @property
    def imath(self):
        return Var(r'\imath')
    @property
    def jmath(self):
        return Var(r'\jmath')
    @property
    def ell(self):
        return Var(r'\ell')
    @property
    def Bbbk(self):
        return Var(r'\Bbbk')
    @property
    def amalg(self):
        return Var(r'\amalg')
    @property
    def nabla(self):
        return Var(r'\nabla')
    @property
    def mho(self):
        return Var(r'\mho')
    @property
    def partial(self):
        return Var(r'\partial')
    @property
    def eth(self):
        return Var(r'\eth')
    @property
    def hbar(self):
        return Var(r'\hbar')
    @property
    def hslash(self):
        return Var(r'\hslash')
    @property
    def Im(self):
        return Var(r'\Im')
    @property
    def Re(self):
        return Var(r'\Re')
    @property
    def wp(self):
        return Var(r'\wp')
    @property
    def emptyset(self):
        return Var(r'\emptyset')
    @property
    def emptyset(self):
        return Var(r'\emptyset')
    @property
    def varnothing(self):
        return Var(r'\varnothing')
    @property
    def complement(self):
        return Var(r'\complement')
    @property
    def circledS(self):
        return Var(r'\circledS')

"default symbol lookup class, can change name later maybe"
Greek = GreekSymbols()