
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Set.ipynb
from pytex.Variables import Var

class SetSymbols():
    def __init__(self):
        pass
    @property
    def Subset(self):
        return Var(r'\Subset')
    @property
    def sqsubset(self):
        return Var(r'\sqsubset')
    @property
    def triangleleft(self):
        return Var(r'\triangleleft')
    @property
    def blacktriangleleft(self):
        return Var(r'\blacktriangleleft')
    @property
    def supset(self):
        return Var(r'\supset')
    @property
    def Supset(self):
        return Var(r'\Supset')
    @property
    def sqsupset(self):
        return Var(r'\sqsupset')
    @property
    def triangleright(self):
        return Var(r'\triangleright')
    @property
    def blacktriangleright(self):
        return Var(r'\blacktriangleright')
    @property
    def cap(self):
        return Var(r'\cap')
    @property
    def Cap(self):
        return Var(r'\Cap')
    @property
    def sqcap(self):
        return Var(r'\sqcap')
    @property
    def vartriangle(self):
        return Var(r'\vartriangle')
    @property
    def blacktriangle(self):
        return Var(r'\blacktriangle')
    @property
    def cup(self):
        return Var(r'\cup')
    @property
    def Cup(self):
        return Var(r'\Cup')
    @property
    def sqcup(self):
        return Var(r'\sqcup')
    @property
    def triangledown(self):
        return Var(r'\triangledown')
    @property
    def blacktriangledown(self):
        return Var(r'\blacktriangledown')
    @property
    def In(self):
        return Var(r'\in')
    @property
    def subseteq(self):
        return Var(r'\subseteq')
    @property
    def subseteqq(self):
        return Var(r'\subseteqq')
    @property
    def sqsubseteq(self):
        return Var(r'\sqsubseteq')
    @property
    def ni(self):
        return Var(r'\ni')
    @property
    def supseteq(self):
        return Var(r'\supseteq')
    @property
    def supseteqq(self):
        return Var(r'\supseteqq')
    @property
    def sqsupseteq(self):
        return Var(r'\sqsupseteq')
    @property
    def notin(self):
        return Var(r'\notin')
    @property
    def nsubseteq(self):
        return Var(r'\nsubseteq')
    @property
    def subsetneq(self):
        return Var(r'\subsetneq')
    @property
    def varsubsetneq(self):
        return Var(r'\varsubsetneq')
    @property
    def nsubseteqq(self):
        return Var(r'\nsubseteqq')
    @property
    def subsetneqq(self):
        return Var(r'\subsetneqq')
    @property
    def varsubsetneqq(self):
        return Var(r'\varsubsetneqq')
    @property
    def uplus(self):
        return Var(r'\uplus')
    @property
    def nsupseteq(self):
        return Var(r'\nsupseteq')
    @property
    def supsetneq(self):
        return Var(r'\supsetneq')
    @property
    def varsupsetneq(self):
        return Var(r'\varsupsetneq')
    @property
    def nsupseteqq(self):
        return Var(r'\nsupseteqq')
    @property
    def supsetneqq(self):
        return Var(r'\supsetneqq')
    @property
    def varsupsetneqq(self):
        return Var(r'\varsupsetneqq')

Set = SetSymbols()