
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/LatexSeriesFormatter.ipynb
from pytex.LatexInterface.LatexFormatters.LatexBasicFormatter import LatexBasicFormatter
class LatexSeriesFormatter():
    @staticmethod
    def integral(func, wrt, lower=None, upper=None):
        func, wrt, lower, upper = LatexSeriesFormatter.preprocess_args(func, f'd{wrt}', lower, upper)
        return f'\\int{lower}{upper}{func} {wrt}'

    @staticmethod
    def partial_integral(func, wrt, lower=None, upper=None):
        func, wrt, lower, upper = LatexSeriesFormatter.preprocess_args(func, f'\\partial {wrt}',
                                                                       lower, upper)
        return f'\\int{lower}{upper}{func} {wrt}'

    @staticmethod
    def summation(func, wrt, lower=None, upper=None):
        lower = f'{wrt}={lower}' if lower is not None else wrt
        func, _, lower, upper = LatexSeriesFormatter.preprocess_args(func, wrt, lower, upper)
        return f'\\sum{lower}{upper} {func}'

    @staticmethod
    def product(func, wrt, lower=None, upper=None):
        lower = f'{wrt}={lower}' if lower is not None else wrt
        func, _, lower, upper = LatexSeriesFormatter.preprocess_args(func, wrt, lower, upper)
        return f'\\prod{lower}{upper} {func}'

    @staticmethod
    def preprocess_args(func, wrt, lower, upper):
        lower, upper = LatexSeriesFormatter.format_lower_upper(lower, upper)
        func, wrt = LatexBasicFormatter.surround_all_with_braces(func, wrt)
        return func, wrt, lower, upper

    @staticmethod
    def format_lower_upper(lower, upper):
        lower = LatexBasicFormatter.surround_with_braces(lower) if lower is not None else ''
        if lower is not None:
            lower = LatexBasicFormatter.subscript(lower)

        upper = LatexBasicFormatter.surround_with_braces(upper) if upper is not None else ''
        if upper is not None:
            upper = LatexBasicFormatter.superscript(upper)
        return lower, upper