
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/LatexDerivativesFormatter.ipynb
class LatexDerivativesFormatter():
    @staticmethod
    def partial(wrt):
        return LatexBasicFormatter.fraction('\\partial', f'\\partial {wrt}')
    @staticmethod
    def partial_of(wrt, function):
        if(not is_one_word(function)):
            function = LatexBasicFormatter.surround_with_parens(function)
        return LatexBasicFormatter.fraction(f'\\partial {function}', f'\\partial {wrt}')

    @staticmethod
    def derivative(wrt):
        return LatexBasicFormatter.fraction('d', f'd{wrt}')
    @staticmethod
    def derivative_of(wrt, function):
        if(not is_one_word(function)):
            function = LatexBasicFormatter.surround_with_parens(function)
        return LatexBasicFormatter.fraction(f'd({function})', f'd{wrt}')