
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Greek.ipynb
class GreekSymbols():
    def __init__(self):
        pass
    @property
    def beta(self):
        return (r'\beta')
    @property
    def gamma(self):
        return (r'\gamma')
    @property
    def delta(self):
        return (r'\delta')
    @property
    def epsilon(self):
        return (r'\epsilon')
    @property
    def zeta(self):
        return (r'\zeta')
    @property
    def eta(self):
        return (r'\eta')
    @property
    def theta(self):
        return (r'\theta')
    @property
    def iota(self):
        return (r'\iota')
    @property
    def kappa(self):
        return (r'\kappa')
    @property
    def lambd(self):
        return (r'\lambda')
    @property
    def mu(self):
        return (r'\mu')
    @property
    def nu(self):
        return (r'\nu')
    @property
    def xi(self):
        return (r'\xi')
    @property
    def mathrm(self):
        return (r'\mathrm')
    @property
    def pi(self):
        return (r'\pi')
    @property
    def rho(self):
        return (r'\rho')
    @property
    def sigma(self):
        return (r'\sigma')
    @property
    def tau(self):
        return (r'\tau')
    @property
    def upsilon(self):
        return (r'\upsilon')
    @property
    def phi(self):
        return (r'\phi')
    @property
    def chi(self):
        return (r'\chi')
    @property
    def psi(self):
        return (r'\psi')
    @property
    def omega(self):
        return (r'\omega')
    @property
    def varepsilon(self):
        return (r'\varepsilon')
    @property
    def vartheta(self):
        return (r'\vartheta')
    @property
    def varkappa(self):
        return (r'\varkappa')
    @property
    def varpi(self):
        return (r'\varpi')
    @property
    def varrho(self):
        return (r'\varrho')
    @property
    def varphi(self):
        return (r'\varphi')
    @property
    def varsigma(self):
        return (r'\varsigma')
    @property
    def Gamma(self):
        return (r'\Gamma')
    @property
    def Delta(self):
        return (r'\Delta')
    @property
    def Theta(self):
        return (r'\Theta')
    @property
    def Lambda(self):
        return (r'\Lambda')
    @property
    def Upsilon(self):
        return (r'\Upsilon')
    @property
    def Xi(self):
        return (r'\Xi')
    @property
    def Phi(self):
        return (r'\Phi')
    @property
    def Pi(self):
        return (r'\Pi')
    @property
    def Psi(self):
        return (r'\Psi')
    @property
    def Sigma(self):
        return (r'\Sigma')
    @property
    def Omega(self):
        return (r'\Omega')
    @property
    def digamma(self):
        return (r'\digamma')
    @property
    def aleph(self):
        return (r'\aleph')
    @property
    def beth(self):
        return (r'\beth')
    @property
    def gimel(self):
        return (r'\gimel')
    @property
    def daleth(self):
        return (r'\daleth')
    @property
    def forall(self):
        return (r'\forall')
    @property
    def exists(self):
        return (r'\exists')
    @property
    def nexists(self):
        return (r'\nexists')
    @property
    def Finv(self):
        return (r'\Finv')
    @property
    def Game(self):
        return (r'\Game')
    @property
    def backepsilon(self):
        return (r'\backepsilon')
    @property
    def imath(self):
        return (r'\imath')
    @property
    def jmath(self):
        return (r'\jmath')
    @property
    def ell(self):
        return (r'\ell')
    @property
    def Bbbk(self):
        return (r'\Bbbk')
    @property
    def amalg(self):
        return (r'\amalg')
    @property
    def nabla(self):
        return (r'\nabla')
    @property
    def mho(self):
        return (r'\mho')
    @property
    def partial(self):
        return (r'\partial')
    @property
    def eth(self):
        return (r'\eth')
    @property
    def hbar(self):
        return (r'\hbar')
    @property
    def hslash(self):
        return (r'\hslash')
    @property
    def Im(self):
        return (r'\Im')
    @property
    def Re(self):
        return (r'\Re')
    @property
    def wp(self):
        return (r'\wp')
    @property
    def emptyset(self):
        return (r'\emptyset')
    @property
    def emptyset(self):
        return (r'\emptyset')
    @property
    def varnothing(self):
        return (r'\varnothing')
    @property
    def complement(self):
        return (r'\complement')
    @property
    def circledS(self):
        return (r'\circledS')

"default symbol lookup class, can change name later maybe"
Greek = GreekSymbols()