
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Arrow.ipynb
class ArrowsSymbols():
    def __init__(self):
        pass
    @property
    def Leftarrow(self):
        return (r'\Leftarrow')
    @property
    def leftharpoonup(self):
        return (r'\leftharpoonup')
    @property
    def leftharpoondown(self):
        return (r'\leftharpoondown')
    @property
    def leftleftarrows(self):
        return (r'\leftleftarrows')
    @property
    def rightarrow(self):
        return (r'\rightarrow')
    @property
    def Rightarrow(self):
        return (r'\Rightarrow')
    @property
    def rightharpoonup(self):
        return (r'\rightharpoonup')
    @property
    def rightharpoondown(self):
        return (r'\rightharpoondown')
    @property
    def rightrightarrows(self):
        return (r'\rightrightarrows')
    @property
    def uparrow(self):
        return (r'\uparrow')
    @property
    def Uparrow(self):
        return (r'\Uparrow')
    @property
    def upharpoonleft(self):
        return (r'\upharpoonleft')
    @property
    def upharpoonright(self):
        return (r'\upharpoonright')
    @property
    def upuparrows(self):
        return (r'\upuparrows')
    @property
    def downarrow(self):
        return (r'\downarrow')
    @property
    def Downarrow(self):
        return (r'\Downarrow')
    @property
    def downharpoonleft(self):
        return (r'\downharpoonleft')
    @property
    def downharpoonright(self):
        return (r'\downharpoonright')
    @property
    def downdownarrows(self):
        return (r'\downdownarrows')
    @property
    def longleftarrow(self):
        return (r'\longleftarrow')
    @property
    def Longleftarrow(self):
        return (r'\Longleftarrow')
    @property
    def hookleftarrow(self):
        return (r'\hookleftarrow')
    @property
    def leftrightharpoons(self):
        return (r'\leftrightharpoons')
    @property
    def leftrightarrows(self):
        return (r'\leftrightarrows')
    @property
    def Lleftarrow(self):
        return (r'\Lleftarrow')
    @property
    def Lsh(self):
        return (r'\Lsh')
    @property
    def leftarrowtail(self):
        return (r'\leftarrowtail')
    @property
    def twoheadleftarrow(self):
        return (r'\twoheadleftarrow')
    @property
    def curvearrowleft(self):
        return (r'\curvearrowleft')
    @property
    def circlearrowleft(self):
        return (r'\circlearrowleft')
    @property
    def looparrowleft(self):
        return (r'\looparrowleft')
    @property
    def longrightarrow(self):
        return (r'\longrightarrow')
    @property
    def Longrightarrow(self):
        return (r'\Longrightarrow')
    @property
    def hookrightarrow(self):
        return (r'\hookrightarrow')
    @property
    def rightleftharpoons(self):
        return (r'\rightleftharpoons')
    @property
    def rightleftarrows(self):
        return (r'\rightleftarrows')
    @property
    def Rrightarrow(self):
        return (r'\Rrightarrow')
    @property
    def Rsh(self):
        return (r'\Rsh')
    @property
    def rightarrowtail(self):
        return (r'\rightarrowtail')
    @property
    def twoheadrightarrow(self):
        return (r'\twoheadrightarrow')
    @property
    def curvearrowright(self):
        return (r'\curvearrowright')
    @property
    def circlearrowright(self):
        return (r'\circlearrowright')
    @property
    def looparrowright(self):
        return (r'\looparrowright')
    @property
    def leftrightarrow(self):
        return (r'\leftrightarrow')
    @property
    def longleftrightarrow(self):
        return (r'\longleftrightarrow')
    @property
    def updownarrow(self):
        return (r'\updownarrow')
    @property
    def nleftarrow(self):
        return (r'\nleftarrow')
    @property
    def nrightarrow(self):
        return (r'\nrightarrow')
    @property
    def nleftrightarrow(self):
        return (r'\nleftrightarrow')
    @property
    def Leftrightarrow(self):
        return (r'\Leftrightarrow')
    @property
    def Longleftrightarrow(self):
        return (r'\Longleftrightarrow')
    @property
    def Updownarrow(self):
        return (r'\Updownarrow')
    @property
    def nLeftarrow(self):
        return (r'\nLeftarrow')
    @property
    def nRightarrow(self):
        return (r'\nRightarrow')
    @property
    def nLeftrightarrow(self):
        return (r'\nLeftrightarrow')
    @property
    def mapsto(self):
        return (r'\mapsto')
    @property
    def longmapsto(self):
        return (r'\longmapsto')
    @property
    def multimap(self):
        return (r'\multimap')
    @property
    def rightsquigarrow(self):
        return (r'\rightsquigarrow')
    @property
    def leftrightsquigarrow(self):
        return (r'\leftrightsquigarrow')
    @property
    def swarrow(self):
        return (r'\swarrow')
    @property
    def searrow(self):
        return (r'\searrow')
    @property
    def nwarrow(self):
        return (r'\nwarrow')
    @property
    def nearrow(self):
        return (r'\nearrow')

Arrow = ArrowsSymbols()